"""add info to products and add category table

Revision ID: 29579430351e
Revises: c4bb4e0bd4c9
Create Date: 2024-10-15 21:18:17.917684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29579430351e'
down_revision: Union[str, None] = 'c4bb4e0bd4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.add_column('products', sa.Column('descr', sa.String(), nullable=False))
    op.add_column('products', sa.Column('carb', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('protein', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('fats', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('calories', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('composition', sa.String(), nullable=False))
    op.add_column('products', sa.Column('store_condition', sa.String(), nullable=False))
    op.add_column('products', sa.Column('category', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'category', ['category'], ['category_id'])
    op.add_column('warehouse', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('warehouse', sa.Column('latitude', sa.Float(), nullable=False))
    op.drop_column('warehouse', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('warehouse', 'latitude')
    op.drop_column('warehouse', 'longitude')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category')
    op.drop_column('products', 'store_condition')
    op.drop_column('products', 'composition')
    op.drop_column('products', 'calories')
    op.drop_column('products', 'fats')
    op.drop_column('products', 'protein')
    op.drop_column('products', 'carb')
    op.drop_column('products', 'descr')
    op.drop_table('category')
    # ### end Alembic commands ###
