"""add unit, products

Revision ID: c4bb4e0bd4c9
Revises: e59f60a248f8
Create Date: 2024-09-28 02:45:48.169618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4bb4e0bd4c9'
down_revision: Union[str, None] = 'e59f60a248f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('unit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit'], ['units.unit_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.warehouse_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('units')
    # ### end Alembic commands ###
